### ISSUE TITLE
emails are not sent on dag failures

### ISSUE THREAD

**Issue by tkalir** [data-for-change/anyway-etl#44]

**Comment by OriHoch** [comment]
you can see the error in the failed task log, seems like it fails to connect to the SMTP server, I'll check what's the problem

```
[2023-07-23, 13:20:14 UTC] {email.py:268} INFO - Email alerting: attempt 1
[2023-07-23, 13:20:44 UTC] {email.py:268} INFO - Email alerting: attempt 1
[2023-07-23, 13:21:14 UTC] {taskinstance.py:1839} ERROR - Failed to send email to: ['***', '***', '***']
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1383, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1529, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1589, in _execute_task
    result = execute_callable(context=context)
  File "/srv/anyway_etl_airflow/operators/cli_bash_operator.py", line 37, in execute
    return super(CliBashOperator, self).execute(context)
  File "/usr/local/lib/python3.8/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2239, in email_alert
    send_email(task.email, subject, html_content)
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/email.py", line 78, in send_email
    return backend(
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/email.py", line 270, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1837, in handle_failure
    self.email_alert(error, task)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2241, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/email.py", line 78, in send_email
    return backend(
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/email.py", line 270, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
socket.timeout: timed out
```

**Comment by OriHoch** [comment]
it was using smtp port 25 by default but that's blocked in AWS, so I changed to port 2525, I ran the dag that was failing and it's sending emails now

https://github.com/data-for-change/dfc-k8s/commit/563831bd28e985ec5ace4ab9d8e84f796842179e
